### ISSUE TITLE
Compilation error with stable

### ISSUE THREAD

**Issue by bhase** [bbqsrc/cucumber-rust#7]
Hi,
I am new to Rust and wanted to start with cucumber-rust. I installed rustc and cargo etc. with rustup, that worked fine.
I added then cucumber-rust to my Cargo.toml as described in the Readme and created the files with contents like in Readme, but then it no longer works as expected. When trying to run 'cargo test' it gives the following compiler error:

```
$ cargo test
   Compiling cucumber_rust v0.4.0                                                                                     
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/benjo/.cargo/registry/src/github.com-1ecc6299db9ec823/cucumber_rust-0.4.0/src/lib.rs:9:34
  |
9 | #![cfg_attr(feature = "nightly", feature(set_stdio))]
  |       
```
I think this is the same error as described in #2 but I do not know what to pass to Cargo.
I also tried running nightly (rustup install nightly), but that gives another error:

```
$ cargo +nightly test
   Compiling raytracer_challenge v0.1.0 (/home/benjo/github/raytracer_challenge/rust)                                 
error: no rules expected the token `@`                                                                                
  --> tests/cucumber.rs:21:5                                                                                          
   |                                                                                                                  
21 | /     steps!(::MyWorld => {                                                                                      
22 | |         given "I am trying out Cucumber" |world, step| {                                                       
23 | |             world.foo = "Some string".to_string();                                                             
24 | |             // Set up your context in given steps                                                              
...  |                                                                                                                
47 | |         };                                                                                                     
48 | |     });                                                                                                        
   | |_______^                                                                                                        
   |                                                                                                                  
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

I also fiddled around with --no-default-features or --nocapture but without success. I think this my problem in handling the tool, so please add to the Readme how to run with 'stable'.

**Comment by bbqsrc** [comment]
Hello!

If you want to use `cucumber-rust` with stable, you have to add this to your Cargo.toml:

`cucumber_rust = { version = "0.4.0", default-features = false }`

By default it will attempt to use some internal features to the Rust compiler to capture the stdout and stderr, which are not likely to have alternatives until first-class test framework support is added.

It is a bit strange the error you are receiving, I tend to get the "no rules expected the token `@`" issue in strange circumstances, but how you're using `steps!` looks correct. Assuming you are following the readme, can you show me your `cucumber.rs` file? Perhaps the issue is earlier.

**Comment by bhase** [comment]
Hello,

Thank you for the hint. I added the mentioned line to Cargo.toml, now I get the other failure.

As I am in the office, I need to show you my cucmber.rs later, sorry. But it really looks like there is something wrong with my file.

**Comment by bhase** [comment]
Ok, I am online again :-) The contents of my cucumber.rs (tests/cucumber.rs):
```
#[macro_use]
extern crate cucumber_rust;

pub struct MyWorld {
    // You can use this struct for mutable context in scenarios.
    foo: String
}

impl cucumber_rust::World for MyWorld {}
impl std::default::Default for MyWorld {
    fn default() -> MyWorld {
        // This function is called every time a new scenario is started
        MyWorld { 
            foo: "".to_string()
        }
    }
}

mod example_steps {
    // Any type that implements cucumber_rust::World + Default can be the world
    steps!(::MyWorld => {
        given "I am trying out Cucumber" |world, step| {
            world.foo = "Some string".to_string();
            // Set up your context in given steps
        };

        when "I consider what I am doing" |world, step| {
            // Take actions
            let new_string = format!("{}.", &world.foo);
            world.foo = new_string;
        };

        then "I am interested in ATDD" |world, step| {
            // Check that the outcomes to be observed have occurred
            assert_eq!(world.foo, "Some string.");
        };

        then regex r"^we can (.*) rules with regex$" |world, matches, step| {
            // And access them as an array
            assert_eq!(matches[1], "implement");
        };

        then regex r"^we can also match (\d+) (.+) types$", (usize, String) |world, num, word, step| {
            // `num` will be of type usize, `word` of type String
            assert_eq(num, 42);
            assert_eq(word, "olika");
        };
    });
}

// Declares a before handler function named `something_fn`
before!(something_fn => |scenario| {

});

// Declares an after handler function named `something_fn`
after!(after_thing => |scenario| {

});

// A setup function to be called before everything else
fn setup() {
    
}

cucumber! {
    features: "./features", // Path to our feature files
    world: ::MyWorld, // The world needs to be the same for steps and the main cucumber call
    steps: &[
        example_steps::steps // the `steps!` macro creates a `steps` function in a module
    ],
    setup: setup, // Optional; called once before everything
    before: &[
        before_fn // Optional; called before each scenario
    ], 
    after: &[
        after_fn // Optional; called after each scenario
    ] 
}
```

**Comment by bhase** [comment]
Runnig `cargo +nightly test -v' gave the rustc command, where I could add the -Z option:

```
rustc +nightly --crate-name cucumber tests/cucumber.rs --color always --emit=dep-info,link -C debuginfo=2 --cfg test -C metadata=dcfb3ce4ada35f47 -C extra-filename=-dcfb3ce4ada35f47 --out-dir /home/benjo/github/raytracer_challenge/rust/target/debug/deps -C incremental=/home/benjo/github/raytracer_challenge/rust/target/debug/incremental -L dependency=/home/benjo/github/raytracer_challenge/rust/target/debug/deps --extern cucumber_rust=/home/benjo/github/raytracer_challenge/rust/target/debug/deps/libcucumber_rust-97f6e2ae4f1f0e0c.rlib -Z external-macro-backtrace
error: no rules expected the token `@`
  --> <steps macros>:16:1
   |
1  |        (
   |       _-
   |      |_|
   |     ||_|
   |    |||_|
   |   ||||
2  |   |||| @ gather_steps , $ worldtype : path , $ tests : tt , $ ty : ident regex $ name
3  |   |||| : tt $ body : expr ; ) => {
4  |   |||| $ tests . regex . $ ty . insert (
...    ||||
16 |   |||| @ gather_steps , $ worldtype , $ tests , $ ( $ items ) * ) ; } ; (
   |   |||| ^
...    ||||
57 |   |||| steps ! ( @ gather_steps , $ worldtype , $ tests , $ ( $ items ) * ) ; } ; (
   |   |||| ----------------------------------------------------------------------
   |   |||| |
   |   |||| in this macro invocation (#3)
   |   |||| in this macro invocation (#4)
...    ||||
62 |   |||| Steps < 'a , $ worldtype > = $ crate :: Steps :: new (  ) ; steps ! (
   |  _||||_____________________________________________________________-
63 | | |||| @ gather_steps , $ worldtype , tests , $ ( $ items ) * ) ; tests } } ;
   | | ||||                                                          -           -
   | | ||||__________________________________________________________|___________|
   | | |||___________________________________________________________|___________in this expansion of `steps!` (#1)
   | | ||____________________________________________________________|___________in this expansion of `steps!` (#2)
   | | |_____________________________________________________________|___________in this expansion of `steps!` (#3)
   | |_______________________________________________________________|           in this expansion of `steps!` (#4)
   |                                                                 in this macro invocation (#2)
   | 
  ::: tests/cucumber.rs:21:5
   |
21 | /          steps!(::MyWorld => {
22 | |              given "I am trying out Cucumber" |world, step| {
23 | |                  world.foo = "Some string".to_string();
24 | |                  // Set up your context in given steps
...  |
47 | |              };
48 | |          });
   | |____________- in this macro invocation (#1)

error: aborting due to previous error
```

Maybe this is helpful for you?

**Comment by bbqsrc** [comment]
Mm, there's some kind of regression in the example in the README. Hold tight, gonna fix it. :)

**Comment by bbqsrc** [comment]
Okay, it should be fixed now in 0.4.1, which has been published to crates.io, as well as typos in the README fixed. So copy and paste what's there and tell me how you go. :smile:

**Comment by bhase** [comment]
Great, the updated cucumber.rs is now working for me - thank you!
What I am still missing is the update in README.md to Cargo.toml for usage with stable:

```
cucumber_rust = { version = "0.4.1", default-features = false }
```
